//todo :normal meals
let normalized = [
  //day1
  {
    image: "images/meals/normal",
    breakfast: "vitumbuwa",
    breakfastSide: ["milk", "Eggs"],
    lunch: "nshima",
    lunchside: ["Village chicken", "Spinach"],
    mealSunset: "Fried potatoes ",
    mealSunsetSide: ["Black tea", "Ground nuts"],
    eveningmeal: "nshima",
    eveningmealside: ["Village Chicken", "Beans"],
  },
  //day2
  {
    image: "images/meals/normal",
    breakfast: "Peanut Buns",
    breakfastSide: ["Milk tea", "Banana"],
    lunch: "nshima",
    lunchside: ["Salted Fish", "Kalembula veg"],
    mealSunset: "Brown bread",
    mealSunsetSide: ["Lemon juice", "oranges"],
    eveningmeal: "nshima",
    eveningmealside: ["Salted fish", "Beans"],
  },
  //day3
  {
    image: "images/meals/normal",
    breakfast: "2slices bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["vinkubala", "cabbage"],
    mealSunset: "Fried Casava",
    mealSunsetSide: ["Black tea", "Ground nuts"],
    eveningmeal: "nshima",
    eveningmealside: ["Vinkubala", "Casava leaves"],
  },
  //day4
  {
    images: "images/meals/normal",
    breakfast: "Sample (corn mix)",
    breakfastSide: ["Tea", "orange"],
    lunch: "nshima",
    lunchside: ["Kapenta", "5 years(veg)"],
    mealSunset: "Tobwa",
    mealSunsetSide: ["Water", "Mangoes"],
    eveningmeal: "Rice",
    eveningmealside: ["kapenta", "Green beans"],
  },
  //day5
  {
    image: "images/meals/normal",
    breakfast: "Portage",
    breakfastSide: ["Milk", "Banana"],
    lunch: "nshima",
    lunchside: ["Dry fish", "spinach"],
    mealSunset: "Wild fruits",
    mealSunsetSide: ["Orange juice", "banana"],
    eveningmeal: "nshima",
    eveningmealside: ["Dry fish", "Kalembla"],
  },
  //day6
  {
    image: "images/meals/normal",
    breakfast: "Chapati",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["Boiled fish", "spinach"],
    mealSunset: "Jam Bun",
    mealSunsetSide: ["Lemon juice", "orange"],
    eveningmeal: "nshima",
    eveningmealside: ["Boiled fish", "Beans"],
  },
  //day7
  {
    images: "images/meals/normal",
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["Goat meat", "rep veggies"],
    mealSunset: "Portage",
    mealSunsetSide: ["Tea", "Mangoes"],
    eveningmeal: "Fried Rice",
    eveningmealside: ["Goat meat", "spinach"],
  },
];
let normalWest = [
  //day1
  {
    breakfast: "Brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "Chicken Salad",
    lunchside: ["Water", "Spinach"],
    mealSunset: "Cornflakes",
    mealSunsetSide: ["milk", "banana"],
    eveningmeal: "pesto chicken",
    eveningmealside: ["rice", "brocoli"],
  },
  //day2
  {
    breakfast: "Oat meal",
    breakfastSide: ["Nuts", "Banana"],
    lunch: "Quinoa",
    lunchside: ["Chickpea", "Orange juice"],
    mealSunset: "Brown bread",
    mealSunsetSide: ["Black Tea", "Apple"],
    eveningmeal: "Chickpea Curry",
    eveningmealside: ["Sausage", "pear"],
  },
  //day3
  {
    breakfast: "Yogurt parfait",
    breakfastSide: ["Barries", "Granola"],
    lunch: "Grilled Chicken",
    lunchside: ["Roasted Veg", "Pasta"],
    mealSunset: "Bean soup",
    mealSunsetSide: ["salad", "bread"],
    eveningmeal: "Grilled Chicken",
    eveningmealside: ["Steamed Broccoli", "Sliced berries"],
  },
  //day4
  {
    breakfast: "Wheat-Toast",
    breakfastSide: ["Milk", "Avacado"],
    lunch: "Salmon Salad",
    lunchside: ["Quinoa", "Fruit salad"],
    mealSunset: "Custard portage",
    mealSunsetSide: ["Orange juice", "orange"],
    eveningmeal: "Turkey Meatballs",
    eveningmealside: ["Wheat Pasta", "Blueberries"],
  },
  //day5
  {
    breakfast: "Boiled Egg",
    breakfastSide: ["Black Tea", "Apple"],
    lunch: "Veggie burger",
    lunchside: ["Sweet Potato", "Yogurt"],
    mealSunset: "Cereal",
    mealSunsetSide: ["Milk", "Apple"],
    eveningmeal: "Grilled Steak",
    eveningmealside: ["Roasted Vegetables", "Sliced Mango"],
  },
  //day6
  {
    breakfast: "Fruit Salad",
    breakfastSide: ["Yogurt", "bread"],
    lunch: "Lentil soup",
    lunchside: ["Salad", "wheat bread"],
    mealSunset: "Sweat potato",
    mealSunsetSide: ["Ground nuts", "Black tea"],
    eveningmeal: "Pork Tenderloin",
    eveningmealside: ["Couscous", "Watermelon Slices"],
  },
  //day7
  {
    breakfast: "Cereal",
    breakfastSide: ["milk", "egg"],
    lunch: "Chicken stir-fry",
    lunchside: ["Brown rice", "Edamame"],
    mealSunset: "Oat meal",
    mealSunsetSide: ["Milk", "Banana"],
    eveningmeal: "Baked Cod",
    eveningmealside: ["Quinoa Pilaf", "Kiwi Slices"],
  },
];
let normalMix = [
  //day1
  {
    image: "images/meals/normal",
    breakfast: "vitumbuwa",
    breakfastSide: ["milk", "Eggs"],
    lunch: "nshima",
    lunchside: ["Village chicken", "Spinach"],
    mealSunset: "sweet potatoes ",
    mealSunsetSide: ["Black tea", "Ground nuts"],
    eveningmeal: "nshima",
    eveningmealside: ["Village Chicken", "Beans"],
  },
  //day2
  {
    image: "images/meals/normal",
    breakfast: "butter Buns",
    breakfastSide: ["Milk tea", "Banana"],
    lunch: "nshima",
    lunchside: ["Salted Fish", "Kalembula veg"],
    mealSunset: "Brown bread",
    mealSunsetSide: ["Lemon juice", "oranges"],
    eveningmeal: "nshima",
    eveningmealside: ["Salted fish", "Beans"],
  },
  //day3
  {
    image: "images/meals/normal",
    breakfast: "2 slices bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["vinkubala", "cabbage"],
    mealSunset: "Fried Casava",
    mealSunsetSide: ["Black tea", "Ground nuts"],
    eveningmeal: "nshima",
    eveningmealside: ["Vinkubala", "Casava leaves"],
  },
  //day4
  {
    images: "images/meals/normal",
    breakfast: "Sample(corn mix)",
    breakfastSide: ["Tea", "orange"],
    lunch: "nshima",
    lunchside: ["Kapenta", "5 years(veg)"],
    mealSunset: "Tobwa",
    mealSunsetSide: ["Water", "Mangoes"],
    eveningmeal: "Rice",
    eveningmealside: ["kapenta", "Green beans"],
  },
  //day5
  {
    image: "images/meals/normal",
    breakfast: "Portage",
    breakfastSide: ["Milk", "Banana"],
    lunch: "nshima",
    lunchside: ["Dry fish", "spinach"],
    mealSunset: "Wild fruits",
    mealSunsetSide: ["Orange juice", "banana"],
    eveningmeal: "nshima",
    eveningmealside: ["Dry fish", "Kalembla"],
  },
  //day6
  {
    image: "images/meals/normal",
    breakfast: "Chapati",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["Boiled fish", "spinach"],
    mealSunset: "Jam Bun",
    mealSunsetSide: ["Lemon juice", "orange"],
    eveningmeal: "nshima",
    eveningmealside: ["Boiled fish", "Beans"],
  },
  //day7
  {
    images: "images/meals/normal",
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["Goat meat", "rep veggies"],
    mealSunset: "Portage",
    mealSunsetSide: ["Tea", "Mangoes"],
    eveningmeal: "Fried Rice",
    eveningmealside: ["Goat meat", "spinach"],
  },
  //day8
  {
    breakfast: "Brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "Chicken Salad",
    lunchside: ["Water", "Spinach"],
    mealSunset: "Cornflakes",
    mealSunsetSide: ["milk", "banana"],
    eveningmeal: "pesto chicken",
    eveningmealside: ["rice", "brocoli"],
  },
  //day9
  {
    breakfast: "Oat meal",
    breakfastSide: ["Nuts", "Banana"],
    lunch: "Quinoa",
    lunchside: ["Chickpea", "Orange juice"],
    mealSunset: "Brown bread",
    mealSunsetSide: ["Black Tea", "Apple"],
    eveningmeal: "Chickpea Curry",
    eveningmealside: ["Sausage", "pear"],
  },
  //day10
  {
    breakfast: "Yogurt parfait",
    breakfastSide: ["Barries", "Granola"],
    lunch: "Grilled Chicken",
    lunchside: ["Roasted Veg", "Pasta"],
    mealSunset: "Black bean soup",
    mealSunsetSide: ["salad", "bread"],
    eveningmeal: "Grilled Chicken",
    eveningmealside: ["Broccoli", "Strawberries"],
  },
  //day11
  {
    breakfast: "Wheat-Toast",
    breakfastSide: ["Milk", "Avacado"],
    lunch: "Salmon Salad",
    lunchside: ["Quinoa", "Fruit salad"],
    mealSunset: "Custard portage",
    mealSunsetSide: ["Orange juice", "orange"],
    eveningmeal: "Turkey Meatballs",
    eveningmealside: ["Wheat Pasta", "Blueberries"],
  },
  //day12
  {
    breakfast: "Boiled Egg",
    breakfastSide: ["Black Tea", "Apple"],
    lunch: "Veggie burger",
    lunchside: ["Sweet Potato", "Yogurt"],
    mealSunset: "Cereal",
    mealSunsetSide: ["Milk", "Apple"],
    eveningmeal: "Grilled Steak",
    eveningmealside: ["Roasted Veg", "Sliced Mango"],
  },
  //day13
  {
    breakfast: "Fruit Salad",
    breakfastSide: ["Yogurt", "bread"],
    lunch: "Lentil soup",
    lunchside: ["Salad", "Wheat bread"],
    mealSunset: "Sweat potato",
    mealSunsetSide: ["Ground nuts", "Black tea"],
    eveningmeal: "Pork Tenderloin",
    eveningmealside: ["Couscous", "Watermelon"],
  },
  //day14
  {
    breakfast: "Cereal",
    breakfastSide: ["milk", "egg"],
    lunch: "Chicken stir-fry",
    lunchside: ["Brown rice", "Edamame"],
    mealSunset: "Oat meal",
    mealSunsetSide: ["Milk", "Banana"],
    eveningmeal: "Baked Cod",
    eveningmealside: ["Quinoa Pilaf", "Kiwi Slices"],
  },
];
//todo :vegan meals
let veganized = [
  //day1
  {
    breakfast: "Veggie Omelette",
    breakfastSide: ["Toast", "Berries"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "Avocado Toast",
    breakfastSide: ["Yogurt", "Orange"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
let veganWest = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
let veganMix = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day8
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day9
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day10
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day11
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day12
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day13
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day14
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
//todo :Diabetic meals
let diabeticZed = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
let diabeticWest = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
let diabeticMix = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day8
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day9
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day10
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day11
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day12
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day13
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day14
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
//todo :pescaterian meals
let pescatarianZed = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
let pescatarianWest = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];
let pescatarianMix = [
  //day1
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day2
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day3
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day4
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day5
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day6
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day7
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day8
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day9
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day10
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day11
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day12
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day13
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
  //day14
  {
    breakfast: "brown bread",
    breakfastSide: ["milk", "eggs"],
    lunch: "nshima",
    lunchside: ["village chicken", "spinach"],
    mealSunset: "placeholder",
    mealSunsetSide: ["side1", "side2"],
    eveningmeal: "placeholder",
    eveningmealside: ["side1", "side2"],
  },
];

export {
  normalized,
  normalWest,
  normalMix,
  veganized,
  veganWest,
  veganMix,
  diabeticZed,
  diabeticWest,
  diabeticMix,
  pescatarianZed,
  pescatarianWest,
  pescatarianMix,
};
